name: Generate Metrics

on:
  schedule: # Schedule updates (e.g. every day at 8am)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual runs
  push: # Update on push to main branch
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: 'activity'
          user: ManishBirthlia
          config_timezone: Asia/Kolkata

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Update Metrics' || exit 0
          git push
